EXPERIMENT:
  tag: SM9E1
  name: dp_AE_SM9_1
  edition: 1
  architecture: STAE
  save_model: True
MODEL:
  in_ch: 1
  o_ch: 8
  ks: 3
  embed_dim: 3456
  n_heads: 4
  depth: 4
  sequence_type: LSTM
  p: .3
  n_timepoints: 10
DATASET:
  dataset_name: BSNIP
  image_size: [53, 63, 52, 100]
  clean_up: False
  smooth: True
  imbalanced_flag: False
  n_timepoint: 10
  sampling_rate: 10
  stablize: False
  inp_mode: fMRI
  keep_shape: True
  has_input_channel: True
  valid_ids: [9]
  transform: True
  use_peak_slice: null
  task: DensePrediction
TRAIN:
  epochs: 130
  early_stop: False
  base_lr: 1e-2
  min_lr: 4e-5
  weight_decay: 0.1
  step_lr: 100
  milestones: [5, 15, 50, 100]
  batch_size: 2
  workers: 1
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: PDE
  loss_config: Kuramoto_Sivashinsky
TEST:
  test_size: 2
  test_workers: 0
  shuffling: False
  metric: PDE