EXPERIMENT:
  tag: DM40CMXE1
  name: dp_CMX_DM40_1
  edition: 1
  architecture: CMIXER
  save_model: True
MODEL:
  patch_size: 2
  time_dim: 25
  kernel_size: 3
  depth: 9
  encoder_type: 'space_time_mixture'
  head_dim: [53, 63, 52]
  p: 0.1
DATASET:
  dataset_name: BSNIP
  image_size: [53, 63, 52, 100]
  clean_up: True
  smooth: True
  imbalanced_flag: False
  n_timepoint: 25
  sampling_rate: 4
  stablize: True
  inp_mode: fMRI
  keep_shape: True
  has_input_channel: False
  valid_ids: [13]
  transform: True
  task: DensePrediction
TRAIN:
  epochs: 1000
  early_stop: False
  base_lr: 1e-3
  min_lr: 1e-8
  weight_decay: 0.1
  step_lr: 500
  batch_size: 3
  workers: 4
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: MSE
TEST:
  test_size: 1
  test_workers: 0
  shuffling: False
  metric: MSE