EXPERIMENT:
  tag: DMN13E1
  name: dp_Diffusion_DMN13_1
  edition: 1
  architecture: Diffusion
  save_model: True
MODEL:
  backbone_arch: 'C-UNet' 
  noise_step: 1000
  beta_begin: 1e-4 
  beta_end: 0.02
  img_size: [10, 33, 43, 32]
  machine: 'cpu'
DATASET:
  dataset_name: FBIRN
  image_size: [53, 63, 52, 100]
  clean_up: False
  smooth: True
  imbalanced_flag: False
  n_timepoint: 10
  sampling_rate: 10
  stablize: False
  inp_mode: fMRI
  keep_shape: True
  has_input_channel: True
  valid_ids: [13]
  transform: True
  use_peak_slice: null
  task: DensePrediction
TRAIN:
  epochs: 70
  early_stop: False
  base_lr: 1e-2
  min_lr: 1e-8
  weight_decay: 0.1
  step_lr: 100
  batch_size: 2
  workers: 1
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: MSE
TEST:
  test_size: 1
  test_workers: 0
  shuffling: False
  metric: MSE