EXPERIMENT:
  tag: Recognition
  name: cls_ViT_space_through_time
  edition: 1
  type: ViT
  save_model: True
MODEL:
  img_size: [1, 25, 53, 63, 52]
  patch_size: 7
  in_chans: 1
  n_classes: 3
  embed_dim: 768
  depth: 1
  n_heads: 12
  mlp_ratio: 4
  qkv_bias: True
  p: 0.
  attn_p: 0.
  attn_type: space_through_time
DATASET:
  dataset_name: BSNIP
  image_size: [53, 63, 52, 25]
  min_max_scale: [1,255]
  imbalanced_flag: True
  n_timepoint: 25
  sampling_rate: 4
  normalization_dim: 1
  transform: True
  task: Recognition
TRAIN:
  epochs: 1000
  early_stop: True
  warmup_epochs: 10
  base_lr: 1e-2
  warmup_lr: 3e-7
  min_lr: 5e-6
  weight_decay: 0.01
  batch_size: 2
  workers: 2
  step_lr: 100
  loss: CrossEntropy