EXPERIMENT:
  tag: Recognition
  name: cls_ViT_space_time
  edition: 1
  type: ViT
  save_model: True
MODEL:
  img_size: [53, 63, 52]
  patch_size: 7
  in_chans: 1
  n_classes: 3
  embed_dim: 768
  depth: 3
  n_heads: 12
  mlp_ratio: 4
  qkv_bias: True
  p: 0.3
  attn_p: 0.3
  attn_type: space_time
DATASET:
  dataset_name: BSNIP
  image_size: [53, 63, 52, 100]
  min_max_scale: null
  clean_up: True
  smooth: True
  imbalanced_flag: False
  n_timepoint: 10
  sampling_rate: 10
  normalization_dim: null
  transform: True
  task: Recognition
TRAIN:
  epochs: 200
  early_stop: False
  base_lr: 1e-5
  min_lr: 1e-8
  weight_decay: 0.9
  step_lr: 50
  batch_size: 2
  workers: 2
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: CrossEntropy
TEST:
  test_size: 1
  test_workers: 0
  shuffling: False
  metric: Confusion_Matrix