EXPERIMENT:
  tag: CB13
  name: dp_ViT_CB13_1
  edition: 1
  type: ViT
  save_model: True
MODEL:
  img_size: [53, 63, 3]
  patch_size: 3
  in_chans: 1
  embed_dim: 96
  down_sample_ratio: 1.
  depth: 1
  n_heads: 6
  mlp_ratio: 1
  qkv_bias: True
  p: 0.1
  attn_p: 0.
  attn_type: space_time
  n_timepoints: 100
DATASET:
  dataset_name: BSNIP
  image_size: [53, 63, 52, 100]
  clean_up: True
  smooth: True
  imbalanced_flag: False
  n_timepoint: 100
  sampling_rate: 1
  stablize: True
  inp_mode: fMRI
  keep_shape: True
  has_input_channel: True
  valid_ids: [13]
  transform: True
  choose_peak_slice: True
  task: DensePrediction
TRAIN:
  epochs: 150
  early_stop: False
  base_lr: 1e-3
  min_lr: 1e-8
  weight_decay: 0.1
  step_lr: 100
  batch_size: 2
  workers: 1
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: MSE
TEST:
  test_size: 1
  test_workers: 0
  shuffling: False
  metric: MSE