EXPERIMENT:
  TAG: dense_ViT_12_PearsonCorrelation
  NETWORK_ID: 9
  SAVE_MODEL: True
MODEL:
  TYPE: ViT
  NAME: ScepterDenseViT
  DROP_OUT: True
  DROP_RATE: 0.5
  KERNEL_SIZE: 3
  BATCH_NORM: True
DATASET:
  NAME: UKBiobank
  SAMPLE_SIZE: 100
  IMAGE_SIZE: [53, 63, 52, 490]
  VALID_NETWORKS: [69,53,98,99,45,21,56,3,9,2,11,27,54,66,80,72,16,5,62,15,12,93,20,8,77,68,33,43,70,61,55,63,79,84,96,88,48,81,37,67,38,83,32,40,23,71,17,51,94,13,18,4,7]
TRAIN:
  EPOCHS: 200
  EARLY_STOPP: True
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-4
  WARMUP_LR: 3e-7
  MIN_LR: 5e-6
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 5
  WORKERS: 4
  LOSS: PearsonCorrelation