EXPERIMENT:
  tag: Recognition
  name: dp_ViT_space_time
  edition: 1
  type: ViT
  save_model: True
MODEL:
  img_size: [53, 63, 52]
  patch_size: 7
  in_chans: 1
  n_score_maps: 2
  embed_dim: 768
  depth: 2
  n_heads: 12
  mlp_ratio: 1
  qkv_bias: True
  p: 0.1
  attn_p: 0.
  attn_type: space_time
DATASET:
  dataset_name: BSNIP
  image_size: [53, 63, 52, 100]
  min_max_scale: null
  clean_up: True
  smooth: False
  imbalanced_flag: False
  n_timepoint: 20
  sampling_rate: 5
  normalization_dim: all
  stablize: True
  inp_mode: fMRI
  valid_ids: [9, 2]
  transform: True
  task: DensePrediction
TRAIN:
  epochs: 500
  early_stop: False
  base_lr: 1e-5
  min_lr: 1e-8
  weight_decay: 0.5
  step_lr: 200
  batch_size: 2
  workers: 2
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: Pearson_Correlation
TEST:
  test_size: 1
  test_workers: 0
  shuffling: False
  metric: Cosine_Similarity