EXPERIMENT:
  tag: DMN13E22
  name: dp_ViT_DMN13_22
  edition: 1
  architecture: ViT
  save_model: True
MODEL:
  img_size: [53, 63, 52]
  patch_size: 5
  in_chans: 1
  embed_dim: 96
  down_sample_ratio: 1.
  depth: 1
  n_heads: 6
  mlp_ratio: 1
  qkv_bias: True
  p: 0.3
  attn_p: 0.4
  attn_type: space_time
  n_timepoints: 10
DATASET:
  dataset_name: FBIRN
  image_size: [53, 63, 52, 100]
  clean_up: False
  smooth: True
  imbalanced_flag: False
  n_timepoint: 10
  sampling_rate: 10
  stablize: False
  inp_mode: fMRI
  keep_shape: True
  has_input_channel: True
  valid_ids: [13]
  transform: True
  use_peak_slice: null
  task: DensePrediction
TRAIN:
  epochs: 70
  early_stop: False
  base_lr: 1e-2
  min_lr: 1e-8
  weight_decay: 0.1
  step_lr: 100
  batch_size: 2
  workers: 1
  warmup_epochs: 0
  warmup_lr: 1e-2
  loss: CMP
TEST:
  test_size: 1
  test_workers: 0
  shuffling: False
  metric: CMP